### PR TITLE
final layout updates

### PR DESCRIPTION
**Pull request by nweat**
- Updates to filter panel design and layout
- Added PageObject gem
- Began writing specs

### CODE REVIEW

**Comment by nweat** [comment]
Hey guys, let me know of what you think of the revised search box, I think we can start to work on getting the chart functioning. By the way, can someone please add me to the new project on Codeship! I can only see the webAPI project

**Comment by csrordzhn** [comment]
I like it. 
Did you leave the countries select object in slim without name intentionally? The parameters is being sent blank. I modified it but I just wanted to make sure if this was for demonstration purposes. You should have an invitation to this project codeship dashboard.

**Comment by csrordzhn** [comment]
`search.slim`:==>
`select class = "countries" multiple="multiple" id = "countries" style="width:100%"
          .panel-body
                       option value="BZ" Belize
                h5 Optional Search
                       option value="TW" Taiwan`

**Comment by nweat** [comment]
Not intentional. The name can be the same as the id. We would need to make
modifications because we need to handle multiple countries now and generate
the chart showing # of tours by country.

**Pull request merged**
